// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: route.proto

#include "route.pb.h"
#include "route.grpc.pb.h"

#include <grpc++/impl/codegen/async_stream.h>
#include <grpc++/impl/codegen/async_unary_call.h>
#include <grpc++/impl/codegen/channel_interface.h>
#include <grpc++/impl/codegen/client_unary_call.h>
#include <grpc++/impl/codegen/method_handler_impl.h>
#include <grpc++/impl/codegen/rpc_service_method.h>
#include <grpc++/impl/codegen/service_type.h>
#include <grpc++/impl/codegen/sync_stream.h>
namespace haoxing {
namespace route {

static const char* RoutingService_method_names[] = {
  "/haoxing.route.RoutingService/GetNodeXYZList",
};

std::unique_ptr< RoutingService::Stub> RoutingService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< RoutingService::Stub> stub(new RoutingService::Stub(channel));
  return stub;
}

RoutingService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_GetNodeXYZList_(RoutingService_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status RoutingService::Stub::GetNodeXYZList(::grpc::ClientContext* context, const ::haoxing::route::RequestParam& request, ::haoxing::route::ResponseParam* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_GetNodeXYZList_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::haoxing::route::ResponseParam>* RoutingService::Stub::AsyncGetNodeXYZListRaw(::grpc::ClientContext* context, const ::haoxing::route::RequestParam& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::haoxing::route::ResponseParam>::Create(channel_.get(), cq, rpcmethod_GetNodeXYZList_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::haoxing::route::ResponseParam>* RoutingService::Stub::PrepareAsyncGetNodeXYZListRaw(::grpc::ClientContext* context, const ::haoxing::route::RequestParam& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::haoxing::route::ResponseParam>::Create(channel_.get(), cq, rpcmethod_GetNodeXYZList_, context, request, false);
}

RoutingService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RoutingService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RoutingService::Service, ::haoxing::route::RequestParam, ::haoxing::route::ResponseParam>(
          std::mem_fn(&RoutingService::Service::GetNodeXYZList), this)));
}

RoutingService::Service::~Service() {
}

::grpc::Status RoutingService::Service::GetNodeXYZList(::grpc::ServerContext* context, const ::haoxing::route::RequestParam* request, ::haoxing::route::ResponseParam* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace haoxing
}  // namespace route

